apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.xgeeks.org/team: idp_training
  backstage.io/kubernetes-id: demo-mongo2

namespace: idp-dev
# namespace: demo-mongo2-idp_training-dev

resources:
  - claim-mongodb.yaml
