apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.xgeeks.org/team: idp_training
  backstage.io/kubernetes-id: demo-mongo2

namespace: idp-dev
# namespace: demo-mongo2-idp_training-dev

resources:
  - ../../base
  - ingress.yaml

images:
  # ATENTION name = image.name NOT name = spec.containers[0].name
  - name: ghcr.io/xidp/demo-mongo2
    newTag: v0.1.0

replicas:
  - name: demo-mongo2 # the deployment name
    count: 1
